name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out JSOPA'
        uses: actions/checkout@v3
        with:
          path: jsopa
          ref: ${{ github.ref }}
      - name: 'Use `node.js`'
        uses: actions/setup-node@v3
      - name: 'Run `npm i`'
        run: |
          (cd jsopa; npm i)
      - name: 'Build the JSOPA container'
        id: jsopa_container
        run: |
          (cd jsopa; docker build .)
          echo ::set-output name=JSOPA_CONTAINER_ID::$(cd jsopa; docker build -q .)
      - name: 'Generate all `golden`-s'
        run: |
          export JSOPA_CONTAINER_ID=${{ steps.jsopa_container.outputs.JSOPA_CONTAINER_ID }}
          (cd jsopa; ./scripts/gen_all_goldens.sh)
      - name: 'Generate all JavaScript policies'
        run: |
          export JSOPA_CONTAINER_ID=${{ steps.jsopa_container.outputs.JSOPA_CONTAINER_ID }}
          (cd jsopa; ./scripts/gen_all_js.sh)
      - name: '[Re-]Generate all the tests (TODO(dkorolev): Fixme.)'
        run: |
          export JSOPA_CONTAINER_ID=${{ steps.jsopa_container.outputs.JSOPA_CONTAINER_ID }}
          (cd jsopa; ./scripts/gen_all_js_tests.sh)
      - name: 'RUN ALL JS TESTS OUTSIDE DOCKER'
        run: |
          (cd jsopa; ./node_modules/mocha/bin/mocha.js tests/all_tests.js)
      - name: 'RUN ALL JS TESTS IN DOCKER'
        run: |
          export JSOPA_CONTAINER_ID=${{ steps.jsopa_container.outputs.JSOPA_CONTAINER_ID }}
          (cd jsopa; ./scripts/run_all_tests_in_docker.sh)
