name: JavaScript Transpilation Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out Asbyrgi'
        uses: actions/checkout@v3
        with:
          path: asbyrgi
          ref: ${{ github.ref }}
      - name: 'Use `node.js`'
        uses: actions/setup-node@v3
      - name: 'Run `npm i`'
        run: |
          (cd asbyrgi; npm i)
      - name: 'Build the Asbyrgi container'
        id: asbyrgi_container
        run: |
          (cd asbyrgi; docker build .)
          echo ::set-output name=ASBYRGI_CONTAINER_ID::$(cd asbyrgi; docker build -q .)
      - name: 'Generate all `golden`-s'
        run: |
          export ASBYRGI_CONTAINER_ID=${{ steps.asbyrgi_container.outputs.ASBYRGI_CONTAINER_ID }}
          (cd asbyrgi; ./scripts/gen_all_goldens.sh)
      - name: 'Generate all JavaScript policies'
        run: |
          export ASBYRGI_CONTAINER_ID=${{ steps.asbyrgi_container.outputs.ASBYRGI_CONTAINER_ID }}
          (cd asbyrgi; ./scripts/gen_all_js.sh)
      - name: '[Re-]Generate all the tests (TODO(dkorolev): Fixme.)'
        run: |
          export ASBYRGI_CONTAINER_ID=${{ steps.asbyrgi_container.outputs.ASBYRGI_CONTAINER_ID }}
          (cd asbyrgi; ./scripts/gen_all_js_tests.sh)
      - name: 'RUN ALL JS TESTS'
        run: |
          (cd asbyrgi; ./node_modules/mocha/bin/mocha.js tests/all_tests.js)
